name: spider-fofa

on:
  schedule:
    - cron: '*/20 * * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
    
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Install dependencies
        run: pip install selenium requests futures eventlet

      - name: Run fofa
        run: python ${{ github.workspace }}/fofa.py

      - name: Run zoom
        run: python ${{ github.workspace }}/zoom.py
        
      - name: 提交更改
        run: |
          git config --local user.email "zsz520@qq.com"
          git config --local user.name "zsz520"
          git add .
          git commit *.txt -m "Add generated file"
          #git pull --rebase
          git push -f
